#!/bin/bash
# exit if any script fails
set -e

# nav to the notes directory
cd ~/NOTES

today=$(date +"%y%m%d")
filename=$today.md

# if file already exists, open it
if test -f "$filename"; then
	vim $PWD/$filename
	exit 1
fi

# else create file, add it to git, and open it
touch $PWD/$filename
printf "$filename\n-----\n\n" > $PWD/$filename
git add ./$filename 
vim $PWD/$filename
exit 1
